author: Wojciech Danilo
category: Data
default-extensions: [MultiParamTypeClasses, UndecidableInstances, FlexibleInstances,
  FlexibleContexts, DefaultSignatures, ConstraintKinds, LambdaCase, ViewPatterns,
  ScopedTypeVariables, DeriveFunctor, TypeFamilies, TypeOperators, DataKinds, TypeApplications]
dependencies: [base, data-default, old-time, time >= 1.1.3, bytestring >= 0.10.2,
  containers, old-locale, mtl, text >= 0.8, either, template-haskell, lens, ansi-wl-pprint,
  utf8-string]
github: https://github.com/wdanilo/convert
library: {ghc-options: -Wall -O2, source-dirs: src}
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: convert
stability: experimental
synopsis: Safe and unsafe data conversion utilities with strong type-level operation.
  checking.
version: 1.0.23
