author: Wojciech Danilo
category: Data
default-extensions: [ScopedTypeVariables, ConstraintKinds, DataKinds, DefaultSignatures,
  DeriveDataTypeable, DeriveFoldable, DeriveFunctor, DeriveGeneric, DeriveTraversable,
  DoAndIfThenElse, EmptyDataDecls, FlexibleContexts, FlexibleInstances, GeneralizedNewtypeDeriving,
  InstanceSigs, LambdaCase, MultiParamTypeClasses, OverloadedStrings, PackageImports,
  StandaloneDeriving, TemplateHaskell, TupleSections, TypeOperators, ViewPatterns,
  TypeFamilies, TypeApplications]
dependencies: [base, convert, containers, lens]
github: https://github.com/wdanilo/container
library: {ghc-options: -Wall -O2, source-dirs: src}
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: container
stability: experimental
synopsis: Containers abstraction and utilities.
version: 0.3.1
