name: lens-utils
version: 1.4.2
synopsis: Collection of missing lens utilities.
category: Data
license: Apache-2.0
stability: experimental
homepage: https://github.com/luna/lens-utils
bug-reports: https://github.com/luna/lens-utils/issues
author: Luna Team
copyright: Copyright (C) 2018 Luna Team
maintainer: Wojciech Danilo <wojciech.danilo@luna-lang.org>

ghc-options:
- -Wall
- -O2

library:
  source-dirs:
  - src
  dependencies:
  - base >= 4.10 && < 4.12
  - lens
  - template-haskell
  - containers
  - monoid
  - data-default
  - aeson

default-extensions:
- AllowAmbiguousTypes
- ApplicativeDo
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- DuplicateRecordFields
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MonadComprehensions
- MultiWayIf
- NamedWildCards
- NegativeLiterals
- NumDecimals
- OverloadedLabels
- PackageImports
- QuasiQuotes
- PatternSynonyms
- RankNTypes
- RecursiveDo
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- UnicodeSyntax
- ViewPatterns
- LiberalTypeSynonyms
- RelaxedPolyRec
