author: Wojciech Danilo
category: Data, Text
default-extensions: [AllowAmbiguousTypes, ApplicativeDo, Arrows, BangPatterns, BinaryLiterals,
  ConstraintKinds, DataKinds, DefaultSignatures, DeriveDataTypeable, DeriveFoldable,
  DeriveFunctor, DeriveGeneric, DeriveTraversable, DoAndIfThenElse, DuplicateRecordFields,
  EmptyDataDecls, FlexibleContexts, FlexibleInstances, FunctionalDependencies, GeneralizedNewtypeDeriving,
  InstanceSigs, LambdaCase, MonadComprehensions, MultiWayIf, NamedWildCards, NegativeLiterals,
  NoImplicitPrelude, NumDecimals, OverloadedLabels, PackageImports, QuasiQuotes, RankNTypes,
  RecursiveDo, ScopedTypeVariables, StandaloneDeriving, TemplateHaskell, TupleSections,
  TypeApplications, TypeFamilies, TypeFamilyDependencies, TypeOperators, ViewPatterns,
  LiberalTypeSynonyms, RelaxedPolyRec]
dependencies: [base, prologue, dependent-state, text, ansi-terminal, container]
github: https://github.com/luna/terminal-text
library: {ghc-options: -Wall -O2, source-dirs: src}
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: terminal-text
stability: experimental
synopsis: Text data type for styled terminal output, including all standard ANSI effects
  (bold, italic, blinking) and ANSI / 256 / truecolor colors support for Unix and
  Windows (whenever possible).
version: 1.0.1
