author: Wojciech Danilo
category: Data
default-extensions: [MultiParamTypeClasses, UndecidableInstances, FlexibleInstances,
  FlexibleContexts, CPP, DefaultSignatures]
<<<<<<< HEAD
<<<<<<< HEAD
dependencies: [base, containers, template-haskell, lens]
=======
dependencies: [base, old-time, time >= 1.1.3, bytestring >= 0.10.2, containers, old-locale,
  mtl, text >= 0.8, either, template-haskell, lens]
>>>>>>> parent of 3bb8850... Make it build
=======
dependencies: [base, old-time, time, bytestring, containers, old-locale,
  mtl, text, either, template-haskell, lens]
>>>>>>> parent of 049234b... Remove dependencies
github: https://github.com/wdanilo/convert
library: {ghc-options: -Wall -O2, source-dirs: src}
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: convert
stability: experimental
synopsis: Safe and unsafe data conversion utilities with strong type-level operation.
  checking.
<<<<<<< HEAD
version: 1.0.9
=======
version: 1.0.6
>>>>>>> parent of 049234b... Remove dependencies
