author: Wojciech Danilo
category: Data
default-extensions: [ScopedTypeVariables, ConstraintKinds, DataKinds, DefaultSignatures,
  DeriveDataTypeable, DeriveFoldable, DeriveFunctor, DeriveGeneric, DeriveTraversable,
  DoAndIfThenElse, EmptyDataDecls, FlexibleContexts, FlexibleInstances, GeneralizedNewtypeDeriving,
  InstanceSigs, LambdaCase, MultiParamTypeClasses, OverloadedStrings, PackageImports,
  StandaloneDeriving, TemplateHaskell, TupleSections, TypeOperators, ViewPatterns,
  TypeFamilies, TypeApplications]
dependencies: [base, containers, convert, data-default, data-layer, data-prop, deepseq,
  functor-utils, ghc-prim, hashable, lens, lens-utils, mtl, primitive, template-haskell,
  text, transformers, transformers-base, typelevel, unordered-containers, vector,
  data-construction, data-repr]
github: https://github.com/wdanilo/container
library: {ghc-options: -Wall -O2, source-dirs: src}
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: container
stability: experimental
synopsis: Containers abstraction and utilities.
version: 0.2.13
