author: Wojciech Danilo
category: Data
default-extensions: [AllowAmbiguousTypes, ApplicativeDo, Arrows, BangPatterns, BinaryLiterals,
  ConstraintKinds, DataKinds, DefaultSignatures, DeriveDataTypeable, DeriveFoldable,
  DeriveFunctor, DeriveGeneric, DeriveTraversable, DoAndIfThenElse, DuplicateRecordFields,
  EmptyDataDecls, FlexibleContexts, FlexibleInstances, FunctionalDependencies, GeneralizedNewtypeDeriving,
  InstanceSigs, LambdaCase, MonadComprehensions, MultiWayIf, NamedWildCards, NegativeLiterals,
  NoImplicitPrelude, NumDecimals, OverloadedLabels, PackageImports, QuasiQuotes, RankNTypes,
  RecursiveDo, ScopedTypeVariables, StandaloneDeriving, TemplateHaskell, TupleSections,
  TypeApplications, TypeFamilies, TypeFamilyDependencies, TypeOperators, ViewPatterns,
  LiberalTypeSynonyms, RelaxedPolyRec]
dependencies: [base, prologue, text, terminal-text, dependent-state, container]
github: https://github.com/luna/layouting
library: {ghc-options: -Wall -O2, source-dirs: src}
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: layouting
stability: experimental
synopsis: General layouting library. Currently supports layouting 2D areas and can
  be used as a backend for text pretty printing or automatic windows layouting managers.
version: 1.0.3
