resolver: lts-4.1

packages:
- .
- extra-dep: true
  location: {commit: 99776ed4cee181484be7561cff882c73204eaa2d, git: 'https://github.com/wdanilo/typelevel.git'}
extra-deps:
- data-layer-1.0.4
- functor-utils-1.1
- lens-utils-1.0
- convert-1.0.2
- data-construction-1.1
